 
workspace 'SnowplowSwiftDemo.xcworkspace'

use_frameworks!

target 'SnowplowSwiftDemo' do
    platform :ios, '10.0'
    pod 'AgillicSDK', :git => 'https://github.com/Agillic/agillic-ios-sdk.git'
end
